Style/NegatedIf:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Security/Eval:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Lint/RedundantAssignment:
  Enabled: false
Style/UselessAssignment:
  Enabled: false
Style/MultilineBlockChain:
  Enabled: false
Style/Documentation:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Naming/MethodParameterName:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Performance/ChainArrayAllocation:
  Enabled: false
